transitmatters/new-train-tracker

.gitignore
README.md
elm/elm.json
elm/src/Main.elm
package-lock.json
package.json

Writes "Hello World" from a simple elm app.
Right now it uses the simple webserver that comes with elm (`elm reactor`, called by `npm start`). Once we have a backend, we can change that to a real build process.

Frontend Hello World

---

elm/elm.json
elm/src/Main.elm

This change adds a subscription to Time.every so we get new vehicle data every 30000ms.

Implement 30-second period to get new vehicles

---

elm/elm.json
elm/src/Main.elm
server/MbtaApi.py
server/server.py

Get stops in the frontend and list them, just like we list vehicles.
Also uses `RemoteData.WebData` to wrap the vehicles and stops, which makes it easier to handle loading/error states.

Fetch stops

---

elm/elm.json
elm/src/Data.elm
elm/src/Ladder.elm
elm/src/Main.elm
elm/tests/LadderTest.elm
package-lock.json
package.json
server/MbtaApi.py

The layout logic ended up being surprisingly complicated. I pulled it away from the rest of the view code and into its own file `Ladder.elm` so it could be more easily tested (`npm test`).

draw route ladder

---

assets/TM_logo.svg
assets/TM_wordmark.svg
assets/train.svg
elm/src/Main.elm
server/server.py
static/index.html
static/main.css

draw everything

---

server/Pipfile.lock

Upgrade backend python packages in Pipfile.lock

---

elm/src/Main.elm
static/index.html
static/main.css

Sticky header and adjust css, better on mobile

---

.github/workflows/lint.yml

Fixed bug in javascript job

---

Pipfile
server/MbtaApi.py
server/secrets.py
server/update_history_db.py

Title says it all. This adds `update_history_db.py` to be run as a cronjob—it updates a PostgreSQL database called "newtrains" with last seen start and end times, by vehicle.

Add update_history_db.py script for updating sql database of new trains

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
.gitignore
Pipfile
Pipfile.lock
README.md
deploy-on-lightsail.yml
package.json

- Adds `deploy-to-lightsail.yml`, an Ansible playbook that can be used both manually and by GitHub Actions to deploy the latest version of the New Train Tracker on an AWS Lightsail Instance
- Creates new GitHub Action that runs `deploy-to-lightsail.yml` whenever code is merged to master
- Fixes #10 
- Changes CI to mimic manual linting

Added Continuous Deployment to AWS Lightsail

---

deploy-on-lightsail.yml

To avoid hitting MBTA API call limit

cd: added step to copy secrets file

---

server/history/update_history_db.py
server/mbta_api.py

Added timestamps to logging

---

docs/README.md
package.json
server/application.py
server/mbta_api.py
src/components/App.js
src/components/Footer.js
src/components/Header.js
src/main.css

Fixes #60 
Similar to transitmatters/t-performance-dash#68

Adding footer to NTT

---

server/mbta_api.py

Added additional logging timestamp

---

docs/README.md
package.json
server/history/util.py
server/secrets.py

Updated the `README` to include steps for windows installation; updated `util.py` and `secrets.py` to accommodate including a password.

added docs and updates for windows

---

docs/README.md
static/template.html

Added Google Analytics

---

static/template.html

The time has come for NTT too.

Switch from Google Analytics to GoatCounter (NTT)

---

server/mbta_api.py

fix silly typo preventing redline dest as showing A or B

---

server/application.py
server/history/update_history_db.py
server/mbta_api.py

fixes #77 
This is merely a suggestion- there are many easier ways to fix the issue, but i like the separation of API fetching and stat calculation. It also means "test_mode" doesn't need to be passed all the way down. Thoughts?

separate stat calculation

---

.github/workflows/lint.yml

Updated CI configuration

---

pyproject.toml

Bringing it into line with our `package.json`
Ideally we could automate the versioning done in both files somehow based off `git tag`

Updated Poetry config file

---

.flake8
Procfile
package.json

To align with our other apps
Also removed Procfile since we haven't run this on Heroku in quite a while

Updated backend lint config to use .flake8 file

---

.github/workflows/deploy.yml
.github/workflows/lint.yml

Pinned package-lock-utd to a specifc version

---

server/mbta_api.py

fix blue line arrow direction

---

server/mbta_api.py

Reverts transitmatters/new-train-tracker#135

Revert "fix blue line arrow direction"

---

server/mbta_api.py
src/lines.ts

The blue line train tracker terminal stops were reversed

Swap station positions for blue line

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
README.md
devops/deploy-playbook.yml

Changed all 'master' references to 'main'

---

.github/CODEOWNERS

Will continue to own specific files along with others (and feel free to tag me in anything as well)

Removed Nathan from overall codeowners

---

.github/labeler.yml
.github/workflows/label.yml

T4R, please feel free to nitpick `labeler.yml` as I largely copied/edited it from the Data Dashboard, so there are definitely refinements that could be made

Add labeler action to NTT

---

devops/cloudformation.json

Improve tags and bring down costs
- Adding tags to resources
- Switching to GP3 from GP2 for cost savings
Recommend reviewing with whitespace changes ignored: https://github.com/transitmatters/new-train-tracker/pull/174/files?diff=split&w=1

Updating storage type to gp3

---

src/components/LineStats/LineStats.tsx
static/static_data.json

general upkeep and giving big blue the treatment it deserves
updates the stats, adds them to the blue line
run locally

Updated stats and added for Blue Line

---

.gitignore
devops/deploy-playbook.yml
devops/deploy.sh
devops/systemd.conf
poetry.lock
pyproject.toml

Fixes #163 
Should help us track down why the service crashes when it does
- Adds datadog agent to EC2 instance

Add datadog monitoring to new-train-tracker

---

.github/workflows/deploy.yml

oops
Fixes deploy by grabbing DD_API_KEY

Fix deploy env

---

public/static_data.json

Updating with newest data from http://roster.transithistory.org/

Update static data

---

.github/workflows/lint.yml
package-lock.json
package.json
poetry.lock
pyproject.toml
server/.chalice/config.json
src/constants.ts
src/hooks/useMbtaApi.ts
src/hooks/usePrediction.ts
src/prerender.ts

Fixes #200 
We want to handle 429s better, this makes it way way less likely for us to get 429s
- Reduce the API calls by adding cache layer
- Update packages to ensure latest support
Run locally or on beta, compare network tab between prod and this branch, notice how it's lower, but also notice it's still working just as expected!

Reduce unneeded API calls

---

.github/funding.yml
package-lock.json
package.json
server/chalicelib/fleet.py
server/chalicelib/mbta_api.py
src/components/App.tsx
src/components/CategoryTabPicker.tsx
src/components/Header.tsx
src/components/Line.tsx
src/components/LineStats/LineStats.tsx
src/components/TrainDisplay.tsx
src/components/TrainPopover.tsx
src/components/util.ts
src/constants.ts
src/hooks/searchParams.ts
src/hooks/useMbtaApi.ts
src/hooks/usePrediction.ts
src/interpolation.ts
src/labels.tsx
src/lines.ts
src/paths.ts
src/prerender.ts
src/types.ts
tsconfig.json

Improve the typechecking to ensure code safety. Should reduce future bugs and may even resolve a few current ones
Also fixes #227 
- Reduces usage of `any` significantly
- Updates Bezier library to use Typescript
- Removes googly eye tracking
Ensure app runs as expected still, mostly just updates typing to ensure reduced risk of bugs

Improve Typechecking for safety

---

src/hooks/useMbtaApi.ts

We have a few bugs popping up in the NTT, this may fix them
- Checks for empty `allTrains` and returns `null` when empty to better handle things

Fix potential empty trains bug

---

src/components/Footer.tsx

We talked about it in the meeting
Adds a donate link
Trust the process

Add donate link to footer

---

.github/workflows/deploy.yml
.gitignore
deploy.sh
server/cloudformation.json

Improves the tagging and adds cache to static resources
- Adds tagging to the service resources
- Adds cache to the static assets

Improve tagging and cache

---

package-lock.json
poetry.lock
pyproject.toml
server/.chalice/config.json

Keep us modern, fix security issues
- Updates dependencies to reasonable newest

Update packages for July 2025
