elm/elm.json
elm/src/Main.elm

This change allows the Elm side to download Orange line cars from Flask. Renders them initially as an html list.
Thanks @skyqrose for the help!

Frontend: Download orange line cars from Flask

---

server/MbtaApi.py
server/server.py

Previously, only /data/Orange was supported—this change enables data from multiple lines to be downloaded at one time. /data/Orange still works.
i.e. GET /data/[Comma separated route list]

Change routes endpoint to support multiple routes

---

package-lock.json
package.json

I reworked `npm start` so that it uses concurrently to start both the elm watch loop and the python flask watch loop.
A single shell + single command is now all we need for speedy development.

Improve dev cycle with concurrently task

---

server/MbtaApi.py

Change from filter/map to an explicit for loop; fail with a `continue` if the API response doesn't contain properties we need to display correctly (Python KeyError or TypeError).
This is hard to test when the API response is, generally, fine. Slight shot in the dark.

Handle KeyError and TypeError if they occur

---

elm/src/Main.elm

The TM logo in the bottom right corner now links to https://transitmatters.org

Link the TM logo to TM homepage

---

elm/src/Helpers.elm
elm/src/Main.elm
package.json

If there's a vehicle with missing data that we don't know how to handle, ignore that vehicle, and keep showing the other vehicles. (Instead of breaking the app.)
On other errors, like network errors, show a friendlier message.
Adds the --optimize flag which does some small optimizations like shortening variable names, and preventing us from accidentally pushing debug statements to prod. Info on minifying/optimizing the output is in the [official elm docs](https://guide.elm-lang.org/optimization/asset_size.html)

Handle errors better.

---

.github/workflows/lint.yml
README.md
server/MbtaApi.py

- Added GitHub Actions workflow for linting Python files in `server/` and JS files in `src/` (note this will only run on Pull Requests)
- Added lint status badge to `README.md`
- Remove unused dependency from `MbtaApi.py`

Added Python and Javascript linting

---

static/template.html

Some additional html meta tags should help this search result look better:

Add author and description meta tags

---

Pipfile

This probably isn't how we want to address the issue long term. It might not be how we want to address the issue short-term either, but it should serve as a stop-gap measure to keep our site working.
Due to an issue in the parsing algorithm of json-api-doc, the structure of certain API requests from the T (likely just those when a route_pattern's representative trip is running) is causing the json-api-doc library to infinitely recurse. I've opened a PR for this fix here, https://github.com/noplay/json-api-doc/pull/21, but have to wait and see if it gets taken up.
Q: Should I commit Pipfile.lock also?

Use tweaked version of json-api-doc

---

Pipfile
README.md
devops/tracker-nginx.conf
devops/tracker-supervisor.conf

Adding deployment server config files to source control. We'll have to be careful to also update these if we ever make changes on the server.
The nginx conf gets cp'd into /etc/nginx/sites-enabled/
The supervisor conf gets cp'd into /etc/supervisor/conf.d/
Note that the supervisor run command only starts the gunicorn server, so if changes are made, npm build will have to be run manually before restarting supervisor with `sudo supervisorctl reload`.
Am I missing some details? Should some of this info go in README also?

add server deployment config files

---

server/fleet.py
server/history/update_history_db.py
server/routes.py

This PR allows us to start tracking new Silver Line vehicles in the history database, either for internal data-crunching or maybe eventually in a new tab of the Train Tracker UI.
_Test plan:_
- I ran `pipenv run python3 -m server.history.update_history_db` and verified that appropriate vehicle rows were added for the Silver Line (it's helpful to set `test_mode=True` here)
- I ran `npm run start` and checked that the tracker itself is working as expected.

update: Start tracking new SL vehicles in history db

---

docs/LICENSE
docs/README.md
package-lock.json
server/application.py
server/fleet.py
server/history/update_history_db.py
server/mbta_api.py
server/routes.py
src/components/util.js
src/useMbtaApi.js

Minor changes made:
- LICENSE and README updates
- Added a bunch of comments
- Renamed a few functions with references to `cars` changed to `vehicles` since Silver Line buses are tracked now as well
- Renamed `data` function to `trains` since it fetches train data
Less minor changes made:
- Retooled some of the logic in `vehicle_data_for_routes()` and `vehicle_array_is_new()`
The idea behind these changes was to preserve the `test_mode` functionality while ensuring that data for all trains in the tracker was accurate - previous logic defined all trains as new when `test_mode` was active - current logic should still include all trains in `test_mode` but their JSON data should accurately show whether or not they are new
- Removed references to `newOnly` in `getTrainRoutePairsForLine()`
Not …

Slight refactoring of NTT code to prep for additional v3 changes

---

server/secrets.py
src/components/Line.js
src/components/Train.js
src/components/TrainPopover.js
src/lines.js
src/main.css
src/prerender.js

Resolves #61
Finally! The compromise I came up with is that we'll only show the station names on the route of the focused train, which means that we can show the full station name. It gets a little visually busy, but it it works fairly well.
_Screenshot:_
_Test plan:_
- Load the tracker with `?testMode=1` and make sure that all line panes render
- Make sure that selecting different Green Line routes works and shows/hides stations as appropriate
- Make sure tabbing between trains still works

Add station labels to all Green Line stops on focused route

---

static/static_data.json

This PR adds static data about the MBTA fleet for use in the currently-being-developed statistics page specified in #59

Added static data JSON

---

package.json
server/history/update_history_db.py

`mbta_api.vehicle_data_for_routes` updated, and `update_history_db` didn't get the memo :-)
Exception handling removed because the former has its own, so it's fine for `update_history_db` to die if something isn't happy.

Update update_history_db.py to the new mbta_api.py

---

docs/README.md
server/history/recent_sightings.py
server/secrets.py

closes #83
adds a new config flag to optionally disable the database - if it's set to false, the last seen logic will return some dummy data instead of querying the database

Conditionally enable postgres connection

---

server/mbta_api.py

We get this error message sometimes in `reverse_if_stops_out_of_order`, presumably because of transiently bad data from the API:
```
File "/home/ubuntu/new-train-tracker/server/mbta_api.py", line 87, in maybe_reverse
return reverse_if_stops_out_of_order(stops, "Park Street", "Downtown Crossing")
File "/home/ubuntu/new-train-tracker/server/mbta_api.py", line 70, in reverse_if_stops_out_of_order
(index_of_first, index_of_second) = (
RuntimeError: generator raised StopIteration
```
[PEP 479](https://peps.python.org/pep-0479/) says that `StopIteration` raised inside a generator becomes a `RuntimeError` after it bubbles out of the originating stack from. I'm...not exactly sure where there is a generator here, but this appears to be the problem.

fix: Also catch `RuntimeError` in `reverse_if_stops_out_of_order`

---

.eslintrc.js
package-lock.json
package.json
src/index.js
src/lines.ts
src/paths.ts

When merging #105, one of the last steps I did was revert back to react 17. Turns out, that broke things. This PR fixes the build error of being back on React 17, and, fixes some potential build issues we may come into that we discovered with https://github.com/transitmatters/t-performance-dash/pull/202
- Change index.js code back to a react 17 acceptable structure
- Add Typescript eslint plugins and parsers
- Fix linting errors

Fixing build and esbuild for react 17

---

.eslintrc.js
package-lock.json
package.json
tsconfig.json

- Adds two new eslint rules to warn on
- Adds import-eslint-plugin

Adding eslint rules for explicit any and default export

---

server/application.py

I'm working on adding EC2/CloudFront to NTT, and we need to tell CloudFront not to cache responses that update regularly.
Note: [CloudFront reads any of `no-cache`, `no-store`, or `private` as a hint not to cache](https://aws.amazon.com/premiumsupport/knowledge-center/prevent-cloudfront-from-caching-files/). (Unlike browsers, where there is a difference between them)

Add 'Cache-Control: nocache' to / and /trains

---

.github/workflows/lint.yml
docs/README.md

Right now, the README badges display the status of the most recent workflow run, including those on PRs. This means that it sometimes appears that things are failing when they actually aren't. This PR adds a lint run to each push to `master` and updates the badges to only show workflows run against `master` so the badges reflect only the `master` branch.

Change badge display source workflows

---

server/mbta_api.py
server/routes.py

We're not showing trains on the Braintree branch today because we cannot assess their branch assignment with route pattern only. This adds an additional attempt to do it by `stop`.
I also tried to determine it with closest station by physical distance, but that broke JFK/UMass-North Quincy trains because that segment is physically closer to Fields Corner.

Fix Red Line braintree branch 20221029

---

.github/workflows/deploy.yml
.github/workflows/lint.yml

While doing some RRE work I came across this npm package: https://www.npmjs.com/package/package-lock-utd
tl;dr it provides a one-liner command that verifies that package-lock.json is up-to-date
Proposing here to add it to all our CI/CD actions as an extra layer of assurance and to help us keep our dependencies straight

Added package-lock.json check to CI/CD actions

---

.github/workflows/lint.yml
poetry.lock
pyproject.toml

Prepare for Python 3.9 & 3.10
- Adds CI jobs for python 3.9 and 3.10
- Allows python 3.8->3.10
- Updates a few smaller python deps

Prepare new train tracker for python 3.10

---

.github/workflows/lint.yml
README.md
devops/deploy-playbook.yml
package-lock.json
package.json
poetry.lock
pyproject.toml
server/application.py
server/background.py
server/fleet.py
server/healthcheck.py
server/initial_data.py
server/last_seen.py
server/mbta_api.py
server/secrets.py

Chalice now supports 3.11, so we should update all our repos to 3.11 for consistency
Updates Python to 3.11
Test on beta!

Upgrade python to 3.11

---

.github/workflows/deploy.yml
devops/deploy-playbook.yml

GitHub actions had the wrong python version
Runs the deploy with Python 3.11 and Node 18

Ensure deploy is using correct Python

---

src/main.css

See Issue #86 
- Removes CSS styles that set header relative to the view height on shorter screens.
- Replaced 2vh padding around header with constant 1rem
Recreate behavior shown on issue #86

Fix Header Resizing on small screens

---

static/static_data.json

Update train delivery status numbers
Very little, only took delivery of 6 new orange line cars, and one green line car was taken out of service

Update delivery stats

---

package-lock.json
package.json
src/components/AgeTabPicker.tsx
src/components/App.tsx
src/components/LineTabPicker.tsx
src/hooks/searchParams.ts
src/index.tsx
src/main.css

Addresses Issue #148 
Moving the state to the query string also makes it easier to share specific views by and copying the link. Also could be nice to be able to bookmark a specific line + train type.
Adds React Router dependency
Primarily replaces the tabState with customHooks based on the useSearchParams hooks from React Router. Age and Line selection are stored in the query string.
Test changing lines and train ages. Page should stay the same on refresh or from bookmarking.

Save state on refresh, use URL state

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
.gitignore
README.md
devops/deploy-playbook.yml
package-lock.json
package.json
poetry.lock
pyproject.toml
server/mbta_api.py

Fixes #150 and kills time on Amtrak
- Bumps Python version from 3.11 to 3.12
- Change log line to proper Exception to help debug V3 API issues
- Add `devops/ec2-secrets.py` to `.gitignore`
- README updates (@mathcolo this is what I was pinging you about lol)
Currently deployed on beta: https://ntt-beta.labs.transitmatters.org

Bump Python to 3.12

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
README.md
devops/deploy-playbook.yml
devops/deploy.sh
package-lock.json
package.json

Fixes #162 and kills time on Amtrak
- Updates Node from 18 to 20
- Updated the versions of some GitHub Actions
Currently deployed on beta: https://ntt-beta.labs.transitmatters.org/

Upgrade to node 20

---

server/fleet.py
server/mbta_api.py
server/secrets.py
src/labels.tsx
src/main.css
src/types.ts

Closes https://github.com/transitmatters/new-train-tracker/issues/184 
Run locally and verify that the last updated date and predicted departure appear for trains on each line

feat(train-popover): add last updated date and predicted departure

---

devops/cloudformation.json
src/labels.tsx

Fix typo, but also add an instance connect resource so that we can use `ec2-instance-connect` in the deploy script instead of ssh'ing via the public IP. 
Fixes the typo and adds an instance connect resource 
Check to see if the typo is fixed, run a deploy.

fix: typo in labels

---

devops/deploy-playbook.yml
devops/systemd.conf

We were using too much CPU just on monitoring. Using less features to lower overhead/costs
- Reduce datadog config usage
- Add dd-trace to python code
- Fix port clash

Datadog config optimization and fixes

---

.github/workflows/deploy.yml
README.md
deploy.sh
package-lock.json
package.json
server/.chalice/policy.json
server/app.py
server/chalicelib/healthcheck.py
server/chalicelib/last_seen.py
server/chalicelib/s3.py
server/chalicelib/secrets.py
server/cloudformation.json
src/components/Line.tsx

A few things needed to be fixed for the deployment
- Fixes CI deployment
- Fixes last seen time range (moved to dayjs instead of 4 year old library)
- Updated README
- Fixed monitoring of lastseen job

Fixing deployment and last seen

---

.github/CODEOWNERS
.github/labeler.yml
.github/workflows/deploy.yml
deploy.sh
src/components/App.tsx
vite.config.ts

Fixes the deployment and version is footer
- Makes sure footer version is pulled into build
- Removes old `/devops` references in deployment

Actually fixing deployment (real this time)

---

poetry.lock
pyproject.toml

Keeping poetry & dependencies up-to-date for running the train tracker smoothly in the future. Also adding "tzdata" package to allow Windows users to run the app.
Changes [tool.poetry.dev-dependencies] to [tool.poetry.group.dev.dependencies] in the pyproject.toml file. 
Also, for Windows OS, the "tzdata" package is required to get time information for trains in the tracker, so this package is added under [tool.poetry.dev-dependencies].
Confirm these changes by running the train tracker locally! 
Set the current directory to new-train-tracker on your machine with shell command: cd new-train-tracker
Run the program with shell command: npm start
View the tracker in your browser with: [http://localhost:5173/](http://localhost:5173/)

Upgrading poetry dev dependencies section

---

src/components/TrainDisplay.tsx

Previously, 4 car train indicators followed the orientation of the train arrow itself, but now that's been corrected: 
Run locally, and set `isFourCar` to `true` all the time to show the indicators on each train.

fix: rotate 4 car indicator correctly

---

public/static_data.json
src/components/LineStats/LastUpdatedStats.tsx
src/components/LineStats/LineStats.css
src/components/LineStats/LineStats.tsx
src/components/LineStats/LineStatsTable.tsx

Update Delivery stats to make more sense
- Ensure we show Type 9 and Type 10 delivery stats
- Fix Orange line display
- Cleanup code to be easier to maintain

Improve delivery stats for all lines, update to March

---

server/chalicelib/mbta_api.py
src/labels.tsx
src/types.ts

A user requested that we show speed of the trains when available. 
Calculated the rounding to 2 decimal places using the solution found on this [Stack Overflow](https://stackoverflow.com/questions/11832914/how-to-round-to-at-most-2-decimal-places-if-necessary).
Set up a dev instance and click on trains until one has speed value available. It seems to be mostly available on Green Line trains.

Add Speed in Miles Per Hour (#233)
